-- Migration: Populate CIE-10 Catalog
-- Date: 2025-12-31
-- Description: Inserts CIE-10 codes from curated catalog (70 priority codes)

-- =========================================================
-- Insert CIE-10 codes
-- =========================================================

INSERT INTO cie10_catalog (
    code, short_description, full_description, chapter, chapter_code,
    category, is_subcategory, parent_code, is_common, notes
) VALUES
    ('A09', 'Diarrea y gastroenteritis de presunto origen infeccioso', 'Diarrea y gastroenteritis de presunto origen infeccioso (diarrea infecciosa, disentería NE, enteritis infecciosa)', 'I - Enfermedades infecciosas y parasitarias', 'I', 'Enfermedades infecciosas intestinales', FALSE, NULL, TRUE, 'Código muy común en atención primaria'),
    ('B24', 'Enfermedad por VIH, sin otra especificación', 'Enfermedad por virus de la inmunodeficiencia humana [VIH], sin otra especificación', 'I - Enfermedades infecciosas y parasitarias', 'I', 'VIH/SIDA', FALSE, NULL, TRUE, 'Requiere seguimiento especial'),
    ('C50', 'Tumor maligno de la mama', 'Tumor maligno de la mama (neoplasia maligna de mama)', 'II - Neoplasias', 'II', 'Tumores malignos', FALSE, NULL, TRUE, 'Requiere tamización y seguimiento'),
    ('C53', 'Tumor maligno del cuello del útero', 'Tumor maligno del cuello del útero (cáncer de cérvix)', 'II - Neoplasias', 'II', 'Tumores malignos', FALSE, NULL, TRUE, 'Tamización con citología/VPH'),
    ('C61', 'Tumor maligno de la próstata', 'Tumor maligno de la próstata (cáncer de próstata)', 'II - Neoplasias', 'II', 'Tumores malignos', FALSE, NULL, TRUE, 'Tamización en hombres >50 años'),
    ('E10', 'Diabetes mellitus tipo 1', 'Diabetes mellitus tipo 1 (diabetes insulinodependiente)', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Diabetes mellitus', FALSE, NULL, TRUE, 'Requiere insulina desde el diagnóstico'),
    ('E10.9', 'Diabetes mellitus tipo 1 sin complicaciones', 'Diabetes mellitus tipo 1 sin mención de complicación', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Diabetes mellitus', TRUE, 'E10', TRUE, ''),
    ('E11', 'Diabetes mellitus tipo 2', 'Diabetes mellitus tipo 2 (diabetes no insulinodependiente)', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Diabetes mellitus', FALSE, NULL, TRUE, 'Código prioritario para SAGE3280 - Grupo B'),
    ('E11.0', 'Diabetes mellitus tipo 2 con coma', 'Diabetes mellitus tipo 2 con coma (hiperosmolar, hipoglucémico)', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Diabetes mellitus', TRUE, 'E11', FALSE, 'Urgencia médica'),
    ('E11.2', 'Diabetes mellitus tipo 2 con complicaciones renales', 'Diabetes mellitus tipo 2 con complicaciones renales (nefropatía diabética)', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Diabetes mellitus', TRUE, 'E11', TRUE, 'Requiere monitoreo de función renal'),
    ('E11.3', 'Diabetes mellitus tipo 2 con complicaciones oftálmicas', 'Diabetes mellitus tipo 2 con complicaciones oftálmicas (retinopatía diabética)', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Diabetes mellitus', TRUE, 'E11', TRUE, 'Requiere valoración oftalmológica anual'),
    ('E11.4', 'Diabetes mellitus tipo 2 con complicaciones neurológicas', 'Diabetes mellitus tipo 2 con complicaciones neurológicas (neuropatía diabética)', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Diabetes mellitus', TRUE, 'E11', TRUE, 'Neuropatía periférica, pie diabético'),
    ('E11.5', 'Diabetes mellitus tipo 2 con complicaciones circulatorias periféricas', 'Diabetes mellitus tipo 2 con complicaciones circulatorias periféricas (vasculopatía diabética)', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Diabetes mellitus', TRUE, 'E11', TRUE, 'Riesgo de amputación'),
    ('E11.6', 'Diabetes mellitus tipo 2 con otras complicaciones especificadas', 'Diabetes mellitus tipo 2 con otras complicaciones especificadas', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Diabetes mellitus', TRUE, 'E11', TRUE, ''),
    ('E11.7', 'Diabetes mellitus tipo 2 con complicaciones múltiples', 'Diabetes mellitus tipo 2 con complicaciones múltiples', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Diabetes mellitus', TRUE, 'E11', TRUE, 'Requiere manejo multidisciplinario'),
    ('E11.9', 'Diabetes mellitus tipo 2 sin complicaciones', 'Diabetes mellitus tipo 2 sin mención de complicación', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Diabetes mellitus', TRUE, 'E11', TRUE, 'Código más usado para DM2'),
    ('E03', 'Otros hipotiroidismos', 'Otros hipotiroidismos (deficiencia de hormona tiroidea)', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Trastornos de la glándula tiroides', FALSE, NULL, TRUE, 'Requiere reemplazo hormonal'),
    ('E03.9', 'Hipotiroidismo no especificado', 'Hipotiroidismo no especificado', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Trastornos de la glándula tiroides', TRUE, 'E03', TRUE, ''),
    ('E05', 'Tirotoxicosis (hipertiroidismo)', 'Tirotoxicosis [hipertiroidismo] (exceso de hormona tiroidea)', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Trastornos de la glándula tiroides', FALSE, NULL, TRUE, 'Requiere tratamiento especializado'),
    ('E66', 'Obesidad', 'Obesidad (exceso de peso corporal)', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Obesidad y sobrepeso', FALSE, NULL, TRUE, 'Factor de riesgo cardiovascular'),
    ('E66.0', 'Obesidad debida a exceso de calorías', 'Obesidad debida a exceso de calorías', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Obesidad y sobrepeso', TRUE, 'E66', TRUE, ''),
    ('E66.9', 'Obesidad no especificada', 'Obesidad no especificada', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Obesidad y sobrepeso', TRUE, 'E66', TRUE, ''),
    ('E78', 'Trastornos del metabolismo de las lipoproteínas', 'Trastornos del metabolismo de las lipoproteínas y otras lipidemias', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Dislipidemia', FALSE, NULL, TRUE, 'Dislipidemia, colesterol alto'),
    ('E78.0', 'Hipercolesterolemia pura', 'Hipercolesterolemia pura (colesterol elevado)', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Dislipidemia', TRUE, 'E78', TRUE, 'Requiere manejo dietético y/o farmacológico'),
    ('E78.5', 'Hiperlipidemia no especificada', 'Hiperlipidemia no especificada (dislipidemia mixta)', 'IV - Enfermedades endocrinas, nutricionales y metabólicas', 'IV', 'Dislipidemia', TRUE, 'E78', TRUE, ''),
    ('I10', 'Hipertensión esencial (primaria)', 'Hipertensión esencial (primaria) - HTA sin causa identificable', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Enfermedades hipertensivas', FALSE, NULL, TRUE, 'Código prioritario para SAGE3280 - Grupo B. Código más usado para HTA'),
    ('I11', 'Enfermedad cardíaca hipertensiva', 'Enfermedad cardíaca hipertensiva (hipertensión con afectación cardíaca)', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Enfermedades hipertensivas', FALSE, NULL, TRUE, 'HTA con compromiso del corazón'),
    ('I11.9', 'Enfermedad cardíaca hipertensiva sin insuficiencia cardíaca', 'Enfermedad cardíaca hipertensiva sin insuficiencia cardíaca (congestiva)', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Enfermedades hipertensivas', TRUE, 'I11', TRUE, ''),
    ('I12', 'Enfermedad renal hipertensiva', 'Enfermedad renal hipertensiva (hipertensión con compromiso renal)', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Enfermedades hipertensivas', FALSE, NULL, TRUE, 'HTA con daño renal'),
    ('I13', 'Enfermedad cardíaca y renal hipertensiva', 'Enfermedad cardíaca y renal hipertensiva (hipertensión con compromiso cardio-renal)', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Enfermedades hipertensivas', FALSE, NULL, TRUE, 'HTA con daño cardíaco y renal'),
    ('I15', 'Hipertensión secundaria', 'Hipertensión secundaria (HTA con causa identificable)', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Enfermedades hipertensivas', FALSE, NULL, FALSE, 'HTA de causa renal, endocrina, etc.'),
    ('I20', 'Angina de pecho', 'Angina de pecho (dolor precordial isquémico)', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Cardiopatía isquémica', FALSE, NULL, TRUE, 'Requiere evaluación cardiológica'),
    ('I21', 'Infarto agudo del miocardio', 'Infarto agudo del miocardio (ataque cardíaco)', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Cardiopatía isquémica', FALSE, NULL, TRUE, 'Urgencia cardiovascular'),
    ('I25', 'Enfermedad isquémica crónica del corazón', 'Enfermedad isquémica crónica del corazón (cardiopatía isquémica)', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Cardiopatía isquémica', FALSE, NULL, TRUE, 'Incluye antecedente de IAM'),
    ('I25.1', 'Enfermedad aterosclerótica del corazón', 'Enfermedad aterosclerótica del corazón (enfermedad coronaria)', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Cardiopatía isquémica', TRUE, 'I25', TRUE, ''),
    ('I50', 'Insuficiencia cardíaca', 'Insuficiencia cardíaca (falla del corazón)', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Insuficiencia cardíaca', FALSE, NULL, TRUE, 'Requiere seguimiento estrecho'),
    ('I50.0', 'Insuficiencia cardíaca congestiva', 'Insuficiencia cardíaca congestiva (ICC)', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Insuficiencia cardíaca', TRUE, 'I50', TRUE, 'Requiere control de líquidos y peso'),
    ('I50.9', 'Insuficiencia cardíaca no especificada', 'Insuficiencia cardíaca no especificada', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Insuficiencia cardíaca', TRUE, 'I50', TRUE, ''),
    ('I63', 'Infarto cerebral', 'Infarto cerebral (ACV isquémico, derrame cerebral)', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Enfermedad cerebrovascular', FALSE, NULL, TRUE, 'Emergencia neurológica'),
    ('I64', 'Accidente vascular encefálico', 'Accidente vascular encefálico agudo, no especificado como hemorrágico o isquémico', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Enfermedad cerebrovascular', FALSE, NULL, TRUE, 'ACV sin especificar tipo'),
    ('I69', 'Secuelas de enfermedad cerebrovascular', 'Secuelas de enfermedad cerebrovascular (secuelas de ACV)', 'IX - Enfermedades del sistema circulatorio', 'IX', 'Enfermedad cerebrovascular', FALSE, NULL, TRUE, 'Antecedente de ACV'),
    ('J18', 'Neumonía', 'Neumonía, organismo no especificado', 'X - Enfermedades del sistema respiratorio', 'X', 'Infecciones respiratorias bajas', FALSE, NULL, TRUE, 'Requiere antibioticoterapia'),
    ('J44', 'EPOC', 'Enfermedad pulmonar obstructiva crónica (EPOC)', 'X - Enfermedades del sistema respiratorio', 'X', 'Enfermedades crónicas respiratorias', FALSE, NULL, TRUE, 'Código prioritario para SAGE3280 - Grupo B'),
    ('J44.0', 'EPOC con infección respiratoria aguda', 'Enfermedad pulmonar obstructiva crónica con infección aguda de las vías respiratorias inferiores', 'X - Enfermedades del sistema respiratorio', 'X', 'Enfermedades crónicas respiratorias', TRUE, 'J44', TRUE, 'Exacerbación infecciosa'),
    ('J44.1', 'EPOC con exacerbación aguda', 'Enfermedad pulmonar obstructiva crónica con exacerbación aguda, no especificada', 'X - Enfermedades del sistema respiratorio', 'X', 'Enfermedades crónicas respiratorias', TRUE, 'J44', TRUE, 'Crisis de EPOC'),
    ('J44.9', 'EPOC no especificada', 'Enfermedad pulmonar obstructiva crónica, no especificada', 'X - Enfermedades del sistema respiratorio', 'X', 'Enfermedades crónicas respiratorias', TRUE, 'J44', TRUE, ''),
    ('J45', 'Asma', 'Asma bronquial', 'X - Enfermedades del sistema respiratorio', 'X', 'Enfermedades crónicas respiratorias', FALSE, NULL, TRUE, 'Código prioritario para SAGE3280 - Grupo B'),
    ('J45.0', 'Asma predominantemente alérgica', 'Asma predominantemente alérgica (asma extrínseca)', 'X - Enfermedades del sistema respiratorio', 'X', 'Enfermedades crónicas respiratorias', TRUE, 'J45', TRUE, ''),
    ('J45.9', 'Asma no especificada', 'Asma, no especificada', 'X - Enfermedades del sistema respiratorio', 'X', 'Enfermedades crónicas respiratorias', TRUE, 'J45', TRUE, ''),
    ('J46', 'Estado asmático', 'Estado asmático (crisis asmática severa)', 'X - Enfermedades del sistema respiratorio', 'X', 'Enfermedades crónicas respiratorias', FALSE, NULL, TRUE, 'Urgencia respiratoria'),
    ('N18', 'Enfermedad renal crónica (ERC)', 'Enfermedad renal crónica (insuficiencia renal crónica)', 'XIV - Enfermedades del sistema genitourinario', 'XIV', 'Insuficiencia renal', FALSE, NULL, TRUE, 'Código prioritario para SAGE3280 - Grupo B'),
    ('N18.1', 'ERC estadio 1', 'Enfermedad renal crónica, estadio 1 (daño renal con TFG normal ≥90)', 'XIV - Enfermedades del sistema genitourinario', 'XIV', 'Insuficiencia renal', TRUE, 'N18', TRUE, 'TFG ≥90 ml/min/1.73m²'),
    ('N18.2', 'ERC estadio 2', 'Enfermedad renal crónica, estadio 2 (TFG levemente disminuida 60-89)', 'XIV - Enfermedades del sistema genitourinario', 'XIV', 'Insuficiencia renal', TRUE, 'N18', TRUE, 'TFG 60-89 ml/min/1.73m²'),
    ('N18.3', 'ERC estadio 3', 'Enfermedad renal crónica, estadio 3 (TFG moderadamente disminuida 30-59)', 'XIV - Enfermedades del sistema genitourinario', 'XIV', 'Insuficiencia renal', TRUE, 'N18', TRUE, 'TFG 30-59 ml/min/1.73m²'),
    ('N18.4', 'ERC estadio 4', 'Enfermedad renal crónica, estadio 4 (TFG severamente disminuida 15-29)', 'XIV - Enfermedades del sistema genitourinario', 'XIV', 'Insuficiencia renal', TRUE, 'N18', TRUE, 'TFG 15-29 ml/min/1.73m²'),
    ('N18.5', 'ERC estadio 5', 'Enfermedad renal crónica, estadio 5 (falla renal <15)', 'XIV - Enfermedades del sistema genitourinario', 'XIV', 'Insuficiencia renal', TRUE, 'N18', TRUE, 'TFG <15 ml/min/1.73m² - Requiere diálisis o trasplante'),
    ('N18.9', 'ERC no especificada', 'Enfermedad renal crónica, no especificada', 'XIV - Enfermedades del sistema genitourinario', 'XIV', 'Insuficiencia renal', TRUE, 'N18', TRUE, ''),
    ('O10', 'Hipertensión preexistente que complica el embarazo', 'Hipertensión preexistente que complica el embarazo, el parto y el puerperio', 'XV - Embarazo, parto y puerperio', 'XV', 'Trastornos hipertensivos del embarazo', FALSE, NULL, TRUE, 'HTA crónica en embarazo'),
    ('O13', 'Hipertensión gestacional', 'Hipertensión gestacional [inducida por el embarazo] sin proteinuria significativa', 'XV - Embarazo, parto y puerperio', 'XV', 'Trastornos hipertensivos del embarazo', FALSE, NULL, TRUE, 'HTA que aparece en el embarazo'),
    ('O14', 'Preeclampsia', 'Hipertensión gestacional con proteinuria significativa (preeclampsia)', 'XV - Embarazo, parto y puerperio', 'XV', 'Trastornos hipertensivos del embarazo', FALSE, NULL, TRUE, 'Requiere vigilancia estrecha'),
    ('O15', 'Eclampsia', 'Eclampsia (preeclampsia con convulsiones)', 'XV - Embarazo, parto y puerperio', 'XV', 'Trastornos hipertensivos del embarazo', FALSE, NULL, FALSE, 'Urgencia obstétrica'),
    ('O24', 'Diabetes mellitus en el embarazo', 'Diabetes mellitus en el embarazo (diabetes gestacional)', 'XV - Embarazo, parto y puerperio', 'XV', 'Diabetes en el embarazo', FALSE, NULL, TRUE, 'Requiere control glicémico estricto'),
    ('O24.4', 'Diabetes mellitus gestacional', 'Diabetes mellitus gestacional (diabetes que aparece en el embarazo)', 'XV - Embarazo, parto y puerperio', 'XV', 'Diabetes en el embarazo', TRUE, 'O24', TRUE, 'Tamización con PTOG'),
    ('Z00', 'Examen general', 'Examen general e investigación de personas sin quejas o sin diagnóstico informado', 'XXI - Factores que influyen en el estado de salud', 'XXI', 'Exámenes y controles de salud', FALSE, NULL, TRUE, 'Control de salud preventivo'),
    ('Z00.0', 'Examen médico general', 'Examen médico general', 'XXI - Factores que influyen en el estado de salud', 'XXI', 'Exámenes y controles de salud', TRUE, 'Z00', TRUE, 'Chequeo médico'),
    ('Z13', 'Examen especial de pesquisa', 'Examen especial de pesquisa para enfermedades y trastornos (tamización)', 'XXI - Factores que influyen en el estado de salud', 'XXI', 'Exámenes y controles de salud', FALSE, NULL, TRUE, 'Tamización de enfermedades'),
    ('Z34', 'Supervisión de embarazo normal', 'Supervisión de embarazo normal (control prenatal)', 'XXI - Factores que influyen en el estado de salud', 'XXI', 'Atención materna', FALSE, NULL, TRUE, 'Código para controles prenatales'),
    ('Z34.0', 'Supervisión de primer embarazo normal', 'Supervisión de primer embarazo normal (control prenatal primigestante)', 'XXI - Factores que influyen en el estado de salud', 'XXI', 'Atención materna', TRUE, 'Z34', TRUE, ''),
    ('Z71', 'Asesoramiento', 'Personas en contacto con los servicios de salud por otras razones de asesoramiento', 'XXI - Factores que influyen en el estado de salud', 'XXI', 'Consejería y asesoramiento', FALSE, NULL, TRUE, 'Educación en salud'),
    ('Z71.3', 'Asesoramiento y supervisión dietética', 'Asesoramiento y supervisión dietética (consejería nutricional)', 'XXI - Factores que influyen en el estado de salud', 'XXI', 'Consejería y asesoramiento', TRUE, 'Z71', TRUE, 'Educación nutricional')
ON CONFLICT (code) DO UPDATE SET
    short_description = EXCLUDED.short_description,
    full_description = EXCLUDED.full_description,
    chapter = EXCLUDED.chapter,
    chapter_code = EXCLUDED.chapter_code,
    category = EXCLUDED.category,
    is_subcategory = EXCLUDED.is_subcategory,
    parent_code = EXCLUDED.parent_code,
    is_common = EXCLUDED.is_common,
    notes = EXCLUDED.notes,
    updated_at = CURRENT_TIMESTAMP;

COMMIT;
